Updated issue templates
fossasia/open-event-ios pull request #136
Opened 2019-01-20 09:18 UTC by dilum1995

I have created two issue templates, to report a bug or to request a new feature/enhancement. 

This task was listed under issue #131

2019-01-20 10:42 UTC, SIMRAN1 reviewed
LGTM! @jogendra please review!

2019-01-24 09:04 UTC, jogendra requested changes
Just small changes and you are fine!

2019-01-24 09:04 UTC, jogendra commented on .github/ISSUE_TEMPLATE/feature_request.md
> +about: Suggest an idea for Open Event ios
Change `ios` to `iOS`

2019-01-24 09:04 UTC, jogendra commented on .github/ISSUE_TEMPLATE/let-s-report-a-bug.md
> +
Please add Xcode version too!

2019-01-25 17:35 UTC, dilum1995 commented on .github/ISSUE_TEMPLATE/feature_request.md
> +about: Suggest an idea for Open Event ios
Okay I will add that

2019-01-25 17:35 UTC, dilum1995 commented on .github/ISSUE_TEMPLATE/let-s-report-a-bug.md
> +
Sure

2019-01-25 17:38 UTC, isuruAb approved these changes

2019-01-25 17:42 UTC, dilum1995 commented
@jogendra updated the issue templates according to your review.

2019-01-25 17:45 UTC, jogendra approved these changes

2019-01-25 17:56 UTC, merged