Add the new functionality in More View controller.
fossasia/open-event-ios pull request #57
Opened 2018-04-28 22:48 UTC by baquer

Added the new functionality of Tell a friend  in MoreViewController.

![screen shot 2018-04-29 at 4 05 53 am](https://user-images.githubusercontent.com/32494694/39401516-336633b2-4b64-11e8-8e29-52ce7fcdf853.png)

2018-05-03 13:29 UTC, jogendra requested changes

2018-05-03 13:29 UTC, imjog commented on FOSSAsia/MoreViewController.swift
> +            let mailVc = configureMailComposeViewController(recipient: "",
Please add some other methods like message etc. Have a look at WhatsApp **Tell a friend** feature.

2018-05-03 15:56 UTC, baquer commented on FOSSAsia/MoreViewController.swift
> +            let mailVc = configureMailComposeViewController(recipient: "",
i will update add other methods like message , facebook etc.

2018-05-11 21:33 UTC, baquer commented
![screen shot 2018-05-12 at 2 57 23 am](https://user-images.githubusercontent.com/32494694/39947804-e5e27ed4-5590-11e8-806a-b2d3086885e7.png)
![screen shot 2018-05-12 at 2 57 27 am](https://user-images.githubusercontent.com/32494694/39947808-e7824512-5590-11e8-878b-70c85b48695b.png)
![screen shot 2018-05-12 at 2 57 55 am](https://user-images.githubusercontent.com/32494694/39947809-e7e76f8c-5590-11e8-86e7-a2a12f7d0559.png)

2018-05-12 08:45 UTC, baquer commented
@mariobehling , @imjog review the PR.

2018-05-13 08:33 UTC, chashmeetsingh reviewed
Why not use `UIActivityViewController` to share data with all the applications which can support sharing instead of only having 3 options?

2018-05-14 11:15 UTC, baquer commented
@chashmeetsingh, @imjog proposed to  make this as like in WhatsApp so thats why i don't use UIActivityViewController
![img_9326 2](https://user-images.githubusercontent.com/32494694/39994156-088d665e-5796-11e8-9b1d-0be79d24ec15.PNG)

2018-05-15 06:23 UTC, jogendra requested changes
@baquer 
- WhatsApp is checking whether user's phone is having Facebook, Twitter etc installed or not and show the sharing options according to the availability of Applications and the `More` action is serving the purpose @chashmeetsingh talking about. The same we want to implement here.
- Replace the icon with some png, the current image is showing white corner when we tap on `Tell a Friend` action.
- Do not open messages with empty message string. Use some placeholder text.

2018-05-18 18:11 UTC, baquer commented
ok

2018-05-22 08:20 UTC, baquer commented
@imjog to see the Message example in action, we  have to run it on an actual device, because the Simulator is unable to send text messages, so please check it using actual device as i performed it on simulator.

2018-05-24 02:43 UTC, SIMRAN1 reviewed
@baquer please resolve the failing test!

2018-05-27 19:14 UTC, baquer commented
@imjog  i tried to resolve the conflict but UITest and other stuff are working fine, don't know where this failing test is occurring , can you help me to find out ?

2018-05-27 20:14 UTC, jogendra reviewed
@baquer Test is failing because of `UIRefreshControl()` which is using outside the main thread which is not allowed. See how @SIMRAN1 solved it in #70. Also put  `UIRefreshControl()` in `DispatchQueue.main.async`.

2018-05-27 20:18 UTC, imjog commented
@baquer Also please look into the changes I requested in last review:

> - WhatsApp is checking whether user's phone is having Facebook, Twitter etc installed or not and show the sharing options according to the availability of Applications and the `More` action is serving the purpose @chashmeetsingh talking about. The same we want to implement here.
> - Replace the icon with some png, the current image is showing white corner when we tap on `Tell a Friend` action.

2018-05-27 20:25 UTC, baquer commented
ok will look into it.

2018-05-27 20:39 UTC, baquer commented
@imjog if we use UIActivityViewController then , it will automatically pop up the options which are available for  share , but then the problem arises that , how can we implement the "Subject "and "body" in the mail and messages for sharing ?

2018-05-27 21:13 UTC, imjog commented
@baquer 
- Look at the WhatsApp tell a friend feature, they are doing that in `UIActivityViewController` (More) too. You can do this in `UIActivityViewController` too, [see here](https://stackoverflow.com/questions/41695840/add-subject-on-email-by-share-uiactivityviewcontroller-in-swift).

- Also you can easily check whether particular app is installed on user's iPhone or not.

- I resolved failing tests in #73. Wait till it merge

- Add [WIP] before PR title till the work is finished. eg. _[WIP] Add the new functionality in More View controller._

2018-05-27 21:16 UTC, baquer commented
@imjog  thanks.

2018-05-29 19:24 UTC, closed without merging