Adding screenshots in README.md
fossasia/open-event-ios pull request #69
Opened 2018-05-23 04:08 UTC by SIMRAN1

Fixes #65 
Added screenshots in Readme.md.

2018-05-25 21:30 UTC, SIMRAN1 commented
@imjog I have added screenshots in README but build is failing!

2018-05-26 05:08 UTC, jogendra requested changes
- Solve the Option issue showing in screenshots
- Add screenshot in 2x2 table not 3x1

2018-05-26 13:18 UTC, SIMRAN1 commented
okk @imjog !!

2018-05-27 21:14 UTC, imjog commented
@SIMRAN1 Please check the resolved failing tests: #73

2018-05-28 04:24 UTC, ghost commented
Hi @SIMRAN1!

It looks like one or more of your builds have failed.
I've added the relevant info below to save you some time.

- [Build 125.1](https://travis-ci.org/fossasia/open-event-ios/jobs/384573876) has `failed`

2018-05-28 12:07 UTC, SIMRAN1 commented
@imjog done the changes.Now screenshots are 9 so I think 3*3 would be better!

2018-05-28 15:46 UTC, imjog commented
@SIMRAN1 Screenshot number **2, 5, 6 and 7** are unnecessary. They are copies or not need to add them to README. Purpose of Readme is to give an overview of an app, not the whole screens. Keep **4** screenshots, 4 is enough.
Do not give height or width to them in markdown, add them using `<table>`, they will adjust according to the screen (Last screenshot is squashing). Do not waste time on little things that are low priority, please work on the issues that make app better. thank you

2018-05-28 15:47 UTC, jogendra reviewed
@SIMRAN1 Screenshot number **2, 5, 6 and 7** are unnecessary. They are copies or not need to add them to README. Purpose of Readme is to give an overview of an app, not the whole screens. Keep **4** screenshots, 4 is enough.
Do not give height or width to them in markdown, add them using `<table>`, they will adjust according to the screen (Last screenshot is squashing). Do not waste time on little things that are low priority, please work on the issues that make app better. thank you

2018-05-28 15:54 UTC, SIMRAN1 commented
okk @imjog .Actually I was busy with my exams . I am making a plan to make the app better !!

2018-06-05 20:45 UTC, chashmeetsingh commented
Try adding screenshots of any one device like iPhone X plus make sure the height of all the screenshots is the same.

2018-06-06 01:04 UTC, SIMRAN1 commented
okk @chashmeetsingh !!

2018-06-08 04:51 UTC, SIMRAN1 commented
@chashmeetsingh please review and merge it!!

2018-06-11 08:58 UTC, jogendra requested changes
@SIMRAN1 Add two screen in a row, four look odd and squashed. Do not fix height, you can fix width.

2018-06-11 08:58 UTC, imjog commented on README.md
> +<td><img src="docs/_static/images/event-list-details.png"  height = "480" ></td>
Do not fix height, screenshot look squashed.

2018-06-11 10:07 UTC, SIMRAN1 commented on README.md
> +<td><img src="docs/_static/images/event-list-details.png"  height = "480" ></td>
okk @imjog !!

2018-06-12 03:13 UTC, SIMRAN1 commented
@imjog @chashmeetsingh I am closing this PR for now . I will open it when new screens are designed.

2018-06-12 03:13 UTC, closed without merging