adding support for circleci
fossasia/open-event-ios pull request #85
Opened 2018-06-10 05:18 UTC by SIMRAN1

Adding support for circle.yml

2018-06-10 05:23 UTC, ghost commented
Hi @SIMRAN1!

It looks like one or more of your builds have failed.
I've added the relevant info below to save you some time.

- [Build 156.1](https://travis-ci.org/fossasia/open-event-ios/jobs/390306053) has `failed`

2018-06-11 06:10 UTC, SIMRAN1 commented
@imjog please review!!

2018-06-11 06:59 UTC, jogendra requested changes

2018-06-11 06:59 UTC, imjog commented on .circleci/config.yml
> +
remove this line

2018-06-11 07:02 UTC, SIMRAN1 commented on .circleci/config.yml
> +
okk @imjog !!

2018-06-11 07:03 UTC, imjog commented
@mariobehling @chashmeetsingh Please integrate the Cirlce-CI to the repo and remove Travic-CI integration.

2018-06-11 07:05 UTC, SIMRAN1 commented
Done @imjog !!

2018-06-11 07:07 UTC, imjog commented
@SIMRAN1 Remove end-space from the last line too.

2018-06-11 07:45 UTC, jogendra approved these changes
Nice!

2018-06-11 07:50 UTC, SIMRAN1 commented
thanks @imjog !!

2018-06-11 19:04 UTC, merged