adding Signup Functionality
fossasia/open-event-ios pull request #97
Opened 2018-06-29 12:44 UTC by SIMRAN1

Fixes #84
Signup Functionality is Added .Now User can Signup through the app

2018-07-01 12:50 UTC, SIMRAN1 commented
@imjog @chashmeetsingh please review!! @imjog I have solved problem of ScrollView in this PR and tested in simulator!

2018-07-01 15:25 UTC, jogendra commented on FOSSAsia/AuthTabBarViewController.swift
> +        let button = UIButton(type: .custom)
Please use functions and put code inside them and call here. Do not write code in `viewDidLoad`.

2018-07-01 15:31 UTC, jogendra requested changes
- On Signup screen, the spinner is always visible. Only show spinner when it is needed, otherwise keep it hidden.
- Show email field line green only when email is valid, otherwise keeps it red.
- Signup screen is not in `scrollView`.

2018-07-02 07:43 UTC, SIMRAN1 commented
okk @imjog !

2018-07-03 09:13 UTC, SIMRAN1 commented
Here is the link for demonstration https://drive.google.com/open?id=1hhCXRgWuaXsBYkHVWN4_gtYB7zGCgJWV

2018-07-03 09:14 UTC, SIMRAN1 commented
@chashmeetsingh @nikit19 @dreadpool2 @simarsingh24 @imjog please review!

2018-07-03 11:05 UTC, imjog commented
@SIMRAN1 In the video demonstration, it is seen that when the user types their last name, the last name text filed is hiding behind the keyboard. that's what I was pointing the last PR and in this PR. This need to be solved. thanks

2018-07-03 15:23 UTC, SIMRAN1 commented
ok @imjog I will solve it!

2018-07-04 12:26 UTC, SIMRAN1 commented
Done @imjog !

2018-07-04 14:01 UTC, jogendra approved these changes
LGTM :)

2018-07-06 04:25 UTC, chashmeetsingh approved these changes

2018-07-06 04:25 UTC, merged