Adding Login Functionality
fossasia/open-event-ios pull request #99
Opened 2018-07-03 10:52 UTC by SIMRAN1

Fixes #83 
Login Functionality is added[WIP]

2018-07-04 12:26 UTC, SIMRAN1 commented
@chashmeetsingh @imjog please review!

2018-07-04 14:15 UTC, jogendra requested changes
If I enter a wrong email address and password, it is not showing any success or failure message, just disabling the fields. Please look into it.

2018-07-04 14:15 UTC, imjog commented on FOSSAsia/Client.swift
> +            case .failure(let error):
replace `let error` with `_`

2018-07-04 20:31 UTC, SIMRAN1 commented on FOSSAsia/Client.swift
> +            case .failure(let error):
okk @imjog !!

2018-07-04 20:32 UTC, SIMRAN1 commented
okkk @imjog I will resolve it!!

2018-07-07 10:27 UTC, SIMRAN1 commented
Done @imjog !

2018-07-09 14:39 UTC, jogendra approved these changes
Looks good to me! Good work :)

2018-07-09 20:21 UTC, merged